version: "3.8"

services:

  db:
    image: "postgres:12"
    platform: linux/amd64
    container_name: ops-db
    security_opt:
      - no-new-privileges:true  # Resolve semgrep https://sg.run/0n8q
    environment:
      - POSTGRES_PASSWORD=local_password
    read_only: true  # Resolve semgrep https://sg.run/e4JE
    tmpfs: /var/run/postgresql/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend_flask/ops_api/
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: ops-backend
    ports:
      - "8080:8080"
    environment:
      - JWT_PRIVATE_KEY
      - OPS_CONFIG=environment/local.py
    volumes:
      - ./backend_flask/ops_api/ops:/home/app/ops
    depends_on:
         db:
           condition: service_healthy

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: ops-frontend
    environment:
      - REACT_APP_BACKEND_DOMAIN=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/:/home/app
