version: "3.8"

services:

  db:
    image: "postgres:11.6"
    environment:
      - POSTGRES_PASSWORD=local_password

  wait_for_postgres:
    build: .
    command: sh wait-for-postgres.sh
    depends_on:
      - db

  migration:
    build: .
    command: python manage.py migrate
    depends_on:
      - wait_for_postgres

  data:
    build: .
    command: python manage.py loaddata ops_site/fixtures/fake_data.json
    depends_on:
      - migration

  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - data
    command: python manage.py runserver 0.0.0.0:8080
