[tool.black]
line-length = 120
extend-exclude = '''
^(\..*|.*\\.nox\\.*)
'''

[tool.isort]
profile = "black"
src_paths = ["data_tools", "ops_api"]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
skip_glob = ["**/.nox/**"]
