name: "CF CLI Action for Cloud.gov"
description: "Deploy and manage Cloud Gov using the cf cli"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  cf_api:
    description: "Target API Endpoint of Cloud.gov CF; defaults to {https://api.fr.cloud.gov} "
    required: false
    default: https://api.fr.cloud.gov
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_org:
    description: "Target Organization"
    required: true
  cf_space:
    description: "Target Space"
    required: true
  command:
    description: "Command to run using CF CLI"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
