jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup_remote_docker
      - run:         
          name: Run Tests
          command:  docker-compose run web pytest --cov-config=.coveragerc --cov=ops_site --cov-report term-missing
      - run:
          name: Install cf cli
          command: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary" | tar xzv -C $HOME/bin
            cf install-plugin autopilot -f -r CF-Community
      - run:
          name: Deploy to dev
          command: |
            if [[ -n "${CIRCLE_BRANCH}" && "${CIRCLE_BRANCH}" != "master" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $DEV_USER -p $DEV_PASSWORD -o $ORG_NAME -s $SPACE_NAME
              echo "Login successful."
            else
              echo "Skipped"
            fi
