jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - run: python --version
      - run: docker-compose -v
      - run:         
          name: Run Tests
          command: docker-compose run web pytest
