jobs:
  build:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Run Tests
          command: docker-compose run web pytest --cov-config=.coveragerc --cov=ops_site --cov-report term-missing
      - run:
          name: Install cf cli
          command: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary" | tar xzv -C $HOME/bin
      - run:
          name: Deploy to cloud.gov
          command: |
            if [[ -n "${CIRCLE_BRANCH}" && "${CIRCLE_BRANCH}" == "development" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $DEV_USER -p $DEV_PASSWORD -o $ORG_NAME -s $SPACE_NAME
              echo "Login successful."
              cf push opre-ops-test -f manifest.yml
              echo "Deploy successful."
            else
              echo "Skipped"
            fi
