jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup_remote_docker
      - run:         
          name: Run Tests
          command: docker-compose run web pytest
