jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run: python --version
      - run:
            name: Run tests
            command: |
              docker-compose run web pytest