jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup_remote_docker
      - run:         
          name: Run Tests
          command:  docker-compose run web pytest --cov-config=.coveragerc --cov=ops_site ops_site/tests/ --cov-report term-missing
