name: Setup Cloud Foundry
description: Download the cloud foundary binary
runs:
  using: composite
  steps:
    - name: Install CF
      shell: bash
      run: |
        mkdir -p $HOME/bin
        export PATH=$HOME/bin:$PATH
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github -o cf-cli.tgz"
        tar xzv -C $HOME/bin cf-cli.tgz
        cf --version
