name: 'Terraform setup and plan'
description: 'Setup Terraform and creates plan'
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  # azure_creds: 
  #   description: 'Azure SP Creds to use with Terraform'
  #   required: true
  azure_client_id: 
    description: 'Azure client id'
    required: true
  azure_client_secret: 
    description: 'Azure client secret'
    required: true
  azure_subscription_id:
    description: 'Azure subscription id'
    required: true
  azure_tenant_id:
    description: 'Azure tenant id'
    required: true
  terraform_version: 
    description: 'Terraform Version'
    required: true
    default: 1.2.9
  github_token: 
    description: 'GitHub token for auth'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true

runs:
  using: "composite"
  env:
    ARM_CLIENT_ID: ${{ inputs.azure_client_id }}
    ARM_CLIENT_SECRET: ${{ inputs.azure_client_secret }}
    ARM_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}
    ARM_TENANT_ID: ${{ inputs.azure_tenant_id }}
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraforom_version }}
        terraform_wrapper: false
    - name: Setup Environment

    # - id: 'login'
    #   name: 'Login to Azure'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ inputs.azure_creds }} #${{ secrets.AZURE_CREDS }}
    # - id: 'login'
    #   name: 'Login to Azure'
    #   uses: Azure/login@v1
    #   with:
    #     creds: '{"clientId":"${{ inputs.azure_client_id }}","clientSecret":"${{ inputs.azure_client_secret }}","subscriptionId":"${{ inputs.azure_subscription_id }}","tenantId":"${{ inputs.azure_tenant_id }}"}'
    
    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}/tfplan

    - name: Comment Plan
      id: comment-plan
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Plan:

          ```
          ${{ steps.plan.outputs.plan }}
          ```

          Plan saved to GH artifacts.