name: Set up Javascript
description: Installs Node.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@c7a93deeacd27a63bee8be26a3bf77dc8fb6ce05 # tag: v3.5.1
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: Install yarn dependencies
      shell: bash
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
