name: Set up Javascript
description: Installs Node.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@a9893b0cfb0821c9c7b5fec28a6a2e6cdd5e20a4 # tag: v3.5.1
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: Install yarn dependencies
      shell: bash
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
