name: Set up Javascript
description: Installs Node.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@ee36e8b5c0fdd6014a0398aed18ce9876360bd63 # tag: v3.5.1
      with:
        node-version-file: ./frontend/.nvmrc
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: Install yarn dependencies
      shell: bash
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
