name: Set up Javascript
description: Installs Node.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        node-version: 18
        cache: 'bun'
        cache-dependency-path: '**/bun.lockb'
    - name: Install bun dependencies
      shell: bash
      working-directory: ./frontend
      run: bun install --frozen-lockfile
