name: Set up Javascript
description: Installs Node.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: Install yarn dependencies
      shell: bash
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
