name: Set up Javascript
description: Installs Bun.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1.1.1
      with:
        bun-version: 1.0.11
    - name: Install bun dependencies
      shell: bash
      working-directory: ./frontend
      run: bun install
