name: Set up Javascript
description: Installs Bun.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
      with:
        bun-version: 1.0.11
    - name: Install bun dependencies
      shell: bash
      working-directory: ./frontend
      run: bun install
