name: Set up Javascript
description: Installs Bun.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1.2.0
      with:
        bun-version: 1.0.11
    - name: Install bun dependencies
      shell: bash
      working-directory: ./frontend
      run: bun install
