name: Set up Javascript
description: Installs Bun.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7 # v1.0.11
      with:
        bun-version: 1.0.11
    - name: Install bun dependencies
      shell: bash
      working-directory: ./frontend
      run: bun install 
      
