name: Set up Python
description: Installs Python3 and dependencies defined in the Pipfile
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@3faddefb4c02470d61266571df739b19e3a006be # tag: v4.3.0
      with:
        python-version: '3.10'
        cache: pipenv
    - name: Install Pipenv
      shell: bash
      run: pip install pipenv
    - name: Install Pipenv dependencies
      shell: bash
      working-directory: ./backend/ops_api
      run: pipenv install --dev
