name: Set up Python
description: Installs Python3 and dependencies defined in the Pipfile
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # tag: v4.3.0
      with:
        python-version: '3.11'
        cache: pipenv
    - name: Install Pipenv
      shell: bash
      run: pip install pipenv
    - name: Install Pipenv dependencies
      shell: bash
      working-directory: ./backend/ops_api
      run: pipenv install --dev
