name: Set up Python
description: Installs Python3 and dependencies defined in the Pipfile
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@04c1311429f7be71707d8ab66c7af8a14e54b938 # tag: v4.3.0
      with:
        python-version: '3.12'
        cache: pipenv
    - name: Install Pipenv
      shell: bash
      run: pip install pipenv
    - name: Install Pipenv dependencies
      shell: bash
      working-directory: ./backend/ops_api
      run: pipenv install --dev
