name: Set up Python
description: Installs Python3 and dependencies defined in the Pipfile
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@0d5da6a89a3aa5b4dbd48e38b0c9d678b0caa0e5 # tag: v4.3.0
      with:
        python-version: '3.10'
        cache: pipenv
    - name: Install Pipenv
      shell: bash
      run: pip install pipenv
    - name: Install Pipenv dependencies
      shell: bash
      working-directory: ./backend/ops_api
      run: pipenv install --dev
