name: 'Build Matrix'

description: 'Builds components based on matrix configuration'

inputs:
  event: # Event type (e.g., push, pull_request)
    required: true

outputs:
  matrix:
    description: "Matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: 'composite'
  steps:
    - name: Check Event Type
      id: check-event
      run: |
        if [ "${{ inputs.event }}" != "push" ] && [ "${{ inputs.event }}" != "pull_request" ]; then
          echo "Invalid event type. Only 'push' and 'pull_request' are supported."
          exit 1
        fi
      shell: bash

    - name: Set Matrix Outputs
      id: set-matrix
      run: |
        if [ "$GITHUB_BASE_REF" ]; then
          # Pull Request
          git fetch origin $GITHUB_BASE_REF --depth=1
          export DIFF=$(git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA)
          echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
        else
          # Push
          git fetch origin ${{ github.event.before }} --depth=1
          export DIFF=$(git diff --name-only ${{ github.event.before }} $GITHUB_SHA)
          echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
        fi

        components=()
        paths=()
        docker_files=()
        working_dirs=()
        image_names=()

        # Function to add a component
        add_component() {
          components+=("$1")
          paths+=("$2")
          docker_files+=("$3")
          working_dirs+=("$4")
          image_names+=("$5")
        }

        # Check if paths of each component are in the changed files
        if echo "$DIFF" | grep -qE 'backend/models/|backend/ops_api/|backend/Dockerfile.ops-api'; then
          echo "DEBUG: Detected changes for Backend"
          add_component "Backend" "backend/models/** backend/ops_api/** backend/Dockerfile.ops-api" "Dockerfile.ops-api" "backend" "ops-backend"
        else
          echo "DEBUG: No changes detected for Backend"
        fi

        if echo "$DIFF" | grep -qE 'backend/data-tools/|backend/Dockerfile.data-tools'; then
          echo "DEBUG: Detected changes for Data-Tools"
          add_component "Data-Tools" "backend/data-tools/** backend/Dockerfile.data-tools" "Dockerfile.data-tools" "backend" "ops-data-tools"
        else
          echo "DEBUG: No changes detected for Data-Tools"
        fi

        if echo "$DIFF" | grep -qE 'frontend/|frontend/Dockerfile.azure'; then
          echo "DEBUG: Detected changes for Frontend"
          add_component "Frontend" "frontend/** frontend/Dockerfile.azure" "Dockerfile.azure" "frontend" "ops-frontend"
        else
          echo "DEBUG: No changes detected for Frontend"
        fi

        # Debug statements
        echo "DEBUG: DIFF variable content:"
        echo "$DIFF"

        # Debug statements for matrix components
        echo "DEBUG: Components: ${components[@]}"
        echo "DEBUG: Paths: ${paths[@]}"
        echo "DEBUG: Docker Files: ${docker_files[@]}"
        echo "DEBUG: Working Directories: ${working_dirs[@]}"
        echo "DEBUG: Image Names: ${image_names[@]}"

        # Set matrix outputs as JSON
        matrix_json="{\"components\":${components[@]},\"paths\":${paths[@]},\"docker_files\":${docker_files[@]},\"working_dirs\":${working_dirs[@]},\"image_names\":${image_names[@]}}"
        echo "DEBUG: Raw matrix output: $matrix_json"
        echo "::set-output name=matrix::$(echo "$matrix_json" | jq -c)"


      shell: bash
