name: 'Bump and Tag'
description: 'Automatically bumps version for npm packages or OpenAPI specs based on commit messages.'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'chevron-up'
  color: 'blue'

inputs:
  config_type:
    description: 'Type of configuration file ("package.json" or "openapi.yml").'
    default: 'package.json'
    required: false

  config_dir:
    description: 'Custom directory for the configuration file.'
    default: ''
    required: false

  tag-prefix:
    description: 'Prefix that is used for the git tag.'
    default: ''
    required: false

  tag-suffix:
    description: 'Suffix that is used for the git tag.'
    default: ''
    required: false

  version-type:
    description: 'Overrides version type from commit message.'
    default: ''
    required: false

  major-wording:
    description: 'Comma-separated list of keywords that trigger a major version bump.'
    default: 'BREAKING CHANGE,major'
    required: false

  minor-wording:
    description: 'Comma-separated list of keywords that trigger a minor version bump.'
    default: 'feat,minor'
    required: false

  patch-wording:
    description: 'Comma-separated list of keywords that trigger a patch version bump.'
    default: ''
    required: false

  rc-wording:
    description: 'Comma-separated list of keywords that trigger a release candidate version bump.'
    default: 'pre-alpha,pre-beta,pre-rc'
    required: false

  default:
    description: 'Set a default version bump to use.'
    default: 'patch'
    required: false

  preid:
    description: 'Set a custom preid for prerelease builds.'
    default: 'rc'
    required: false

  skip-tag:
    description: 'If true, no tag is added to the git repository.'
    default: 'false'
    required: false

  skip-commit:
    description: 'If true, no commit is made after the version is bumped.'
    default: 'false'
    required: false

  skip-push:
    description: 'If true, skip pushing any commits or tags created after the version bump.'
    default: 'false'
    required: false

  target-branch:
    description: 'The branch to perform the version bump on.'
    default: ''
    required: false

  commit-message:
    description: 'Custom commit message for the version bump commit.'
    default: 'ci: version bump to {{version}}'
    required: false

  bump-policy:
    description: 'Set version bump ignore policy ("all", "ignore", "last-commit").'
    default: 'all'
    required: false

  check-last-commit-only:
    description: 'Check only the last commit message to determine version bump.'
    default: 'false'
    required: false

  custom-git-domain:
    description: 'Set a custom domain of the git instance, useful for self-hosted instances.'
    default: 'github.com'
    required: false

outputs:
  newTag:
    description: 'The newly created tag after version bump.'