name: 'Generate GitHub App Token'
description: 'Generates a GitHub App installation token'
inputs:
  APP_ID:
    description: 'GitHub App ID'
    required: true
  PRIVATE_KEY:
    description: 'GitHub App Private Key'
    required: true
  INSTALLATION_ID:
    description: 'GitHub App Installation ID'
    required: true
outputs:
  token:
    description: 'Generated GitHub App installation token'
runs:
  using: 'node12'
  main: 'index.js'
