name: Run Full Stack
description: Runs the full stack from the docker-compose.yml
runs:
  using: composite
  steps:
    - name: Start Stack
      shell: bash
      run: |
        set -x
        docker-compose down -v
        docker-compose up --build -d
