name: Run Full Stack
description: Runs the full stack from the docker-compose.yml
inputs:
  JWT_KEY:
    description: Key used for generating the JWTs in the backend-api. These should be dev/testing keys only.
    required: true
    default: ''
runs:
  using: composite
  steps:

    - name: Check if inputs.JWT_KEY is set
      shell: bash
      run: |
        if [[ -z "${{ inputs.JWT_KEY }}" ]]; then
          echo "inputs.JWT_KEY is empty or not set!"
          exit 1
        else
          echo "inputs.JWT_KEY is set."
        fi

    - name: Start Stack
      shell: bash
      run: |
        set -x
        export JWT_PRIVATE_KEY=${{ inputs.JWT_KEY }}
        docker compose -f docker-compose.e2e.yml down -v
        docker compose -f docker-compose.e2e.yml up --build -d
