name: Run Full Stack
description: Runs the full stack from the docker-compose.yml
runs:
  using: composite
  steps:

    - name: Check if env.TEST_ENV is set
      shell: bash
      run: |
        export TEST_KEY=$(grep TEST_KEY testing.bak | cut -d'=' -f2)
        if [[ -z "${{ env.TEST_KEY }}" ]]; then
          echo "env.TEST_ENV is empty or not set!"
          exit 1
        else
          echo "env.TEST_ENV is set."
        fi

    - name: Start Stack
      shell: bash
      run: |
        set -x
        export JWT_PRIVATE_KEY=${{ env.TEST_KEY }}
        docker compose -f docker-compose.e2e.yml down -v
        docker compose -f docker-compose.e2e.yml up --build -d
