name: Run Full Stack
description: Runs the full stack from the docker-compose.yml
runs:
  using: composite
  steps:

    - name: Start Stack
      shell: bash
      run: |
        set -x
        export JWT_PRIVATE_KEY="${{ env.JWT_PRIVATE_KEY }}"
        docker compose -f docker-compose.yml down -v
        docker compose -f docker-compose.yml up db data-import backend frontend-static --build -d
