name: Build and Publish ops-python-base Image

on:
  workflow_dispatch:
  push:
    branches:
      - POC-Deploy-Docker
    # paths:
    #   - /backend/Dockerfile.base
    # tags:
    #   - 'v*'
  schedule:
    - cron: "0 0 * * *" # runs every night at midnight UTC

jobs:
  build-and-push:
    # runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build & Publish ops-python-base
    uses: ./.github/workflows/build_reusable.yml
    with:
      image-name: ops-python-base
      docker-file: backend/Dockerfile.base
      docker-context: "{{defaultContext}}"
