name: Create and publish a Data-Tools

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - backend/data-tools/**
  push:
    # branches: [main, develop]
    # paths:
    #   - backend/data-tools/**

jobs:
  build-and-push:
    # runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build & Publish ops-frontend
    uses: ./.github/workflows/build_reusable.yml
    with:
      image-name: ops-data-tools
      docker-file: backend/Dockerfile.cg-data-tools
