name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main, development]
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit_test_reusable.yml

  codeql-analysis:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: CodeQL Scan
    uses: ./.github/workflows/security_codeql.yml

  semgrep-analysis:
    permissions:
      security-events: write
    name: Semgrep Scan
    uses: ./.github/workflows/security_semgrep.yml

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python

      - name: Install backend dependencies
        working-directory: ./backend
        run: pipenv install --dev

      - name: Lint backend
        working-directory: ./backend
        run: pipenv run nox -s lint

      - uses: ./.github/actions/setup-javascript

      - name: Lint frontend
        working-directory: ./frontend
        run: yarn lint
