name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Run backend unit tests
        run: docker-compose run web pytest --cov-config=.coveragerc --cov=ops_site --cov-report term-missing
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile
      - name: Run frontend unit tests
        working-directory: ./frontend
        run: yarn test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Pipenv install
        run: pip install pipenv
      - name: Install backend dependencies
        working-directory: ./backend
        run: pipenv install --dev
      - name: Lint backend
        working-directory: ./backend
        run: pipenv run nox -s lint
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile
      - name: Lint frontend
        working-directory: ./frontend
        run: yarn lint
