name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main, development, staging]
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit_test_reusable.yml

  codeql-analysis:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: CodeQL Scan
    uses: ./.github/workflows/security_codeql.yml

  semgrep-analysis:
    permissions:
      security-events: write
    name: Semgrep Scan
    uses: ./.github/workflows/security_semgrep.yml

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: ./.github/actions/setup-python

      # Not needed here, as this is run in our ^^ setup-python
      # - name: Install backend dependencies
      #   working-directory: ./backend/ops_api
      #   run: pipenv install --dev

      - name: Lint backend
        working-directory: ./backend/ops_api
        run: pipenv run nox -s lint

      - uses: ./.github/actions/setup-javascript

      - name: Lint frontend
        working-directory: ./frontend
        run: yarn lint
