name: Dev Frontend Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - cml/deploy-new-infra
    paths:
      - 'frontend/**'

env:
  TF_IN_AUTOMATION: "True"
  ENVIRONMENT: "dev"
  WORKING_DIR: "frontend"
  DOCKER_FILE: "Dockerfile.azure"

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Build and publish the Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@0f6c180522d02d9e608096c4dcf3b691193b4d44 #v13
        with:
          image_name: ${{ github.repository }}/ops-${{ env.WORKING_DIR }} # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.workspace }}/${{ env.WORKING_DIR }}
          dockerfile: ${{ github.workspace }}/${{ env.WORKING_DIR }}/${{ env.DOCKER_FILE }}
          image_tag: ${{ github.sha }}

  frontend-deploy:
    needs: build
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      
      - uses: twingate/github-action@V1.1
        with:
          service-key: ${{ secrets.TWINGATE_SERVICE_KEY }}

      - name: Terraform Apply
        uses: ./.github/actions/tf-apply
        with:
          terraform_directory: "terraform/eastus/ops/${{ env.ENVIRONMENT }}/stacks/${{ env.WORKING_DIR }}"
          azure_client_id: ${{ secrets.ARM_CLIENT_ID }}
          azure_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tf_vars: |
            {
              "environment": "${{ env.ENVIRONMENT }}",
              "containerImageTag": "${{ github.sha }}",
              "dnsZoneName": "opre-ops.flexion.us",
              "frontendName": "opre-ops-dev-frontend",
              "containerAppEnvName": "opre-ops-dev-app-cae",
              "resourceGroupName": "opre-ops-dev-app-rg",
            }

  