name: Dev Test Tag and Build

on:
  workflow_dispatch:
  push:
    branches:
      - cml/bump-push
    paths:
      - 'frontend/**'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name:  'Automated Version Bump'
        id: version_bump
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'ops-frontend-v'
          PACKAGEJSON_DIR:  'frontend'
      
      - name: Use the New Tag and Version
        run: |
          echo "The new tag is ${{ steps.version_bump.outputs.newTag }}"
          echo "The new tag is ${{ env.newTag }}"
          echo "The new version is ${{ env.newVersion }}"