name: Dev Frontend Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      
env:
  WORKING_DIR: "frontend"
  DOCKER_FILE: "Dockerfile.azure"
  ENVIRONMENT: dev

jobs:
  build-frontend:
    # outputs:
    #   version: ${{ steps.extract_version.outputs.version }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Build and publish the Docker image for ${{ github.repository }}
        uses: ./.github/actions/build-and-push
        with:
          image_name: ${{ github.repository }}/ops-${{ env.WORKING_DIR }} # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.workspace }}/${{ env.WORKING_DIR }}
          dockerfile: ${{ github.workspace }}/${{ env.WORKING_DIR }}/${{ env.DOCKER_FILE }}
          image_tags: "unstable,${{ github.sha }}"

  deploy-frontend: 
    needs: build-frontend

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
   
      - name: Log in to Azure
        uses: azure/login@6b2456866fc08b011acb422a92a4aa20e2c4de32 #v2.1.0
        with:
          creds:  ${{ secrets.AZURE_CREDS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@02d045129c058b13312276b50a552834cf74e2af # v2
        with:
            # azureCredentials: ${{ secrets.AZURE_CREDS }}
            containerAppName: opre-ops-${{ env.ENVIRONMENT }}-${{ env.WORKING_DIR }}
            resourceGroup: opre-ops-${{ env.ENVIRONMENT }}-app-rg
            imageToDeploy: ghcr.io/hhs/opre-ops/ops-${{ env.WORKING_DIR }}:${{ github.sha }}
