name: Dev Backend Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      
env:
  WORKING_DIR: "backend"
  DT_DOCKER_FILE: "Dockerfile.data-tools-import"
  BE_DOCKER_FILE: "Dockerfile.ops-api"
  ENVIRONMENT: dev

jobs:
  build-data-tools:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      
      - name: Build and publish the Docker image for ${{ github.repository }}
        uses: ./.github/actions/build-and-push
        with:
          image_name: ${{ github.repository }}/ops-data-tools # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.workspace }}/${{ env.WORKING_DIR }}
          dockerfile: ${{ github.workspace }}/${{ env.WORKING_DIR }}/${{ env.DT_DOCKER_FILE }}
          image_tags: "unstable,${{ github.sha }}"
  
  build-backend:
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install dependencies
        run: npm install
        working-directory: ./.github/actions/bump-and-tag 
        
      - name:  'Automated Version Bump'
        id: version_bump
        uses: ./.github/actions/bump-and-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'ops-backend-v'
          OPENAPI_DIR: 'backend'

      - name: Extract Version
        id: extract_version
        run: |
          # Log the original tag output to see what is being processed
          echo "Original newTag: ${{ steps.version_bump.outputs.newTag }}"
          
          # Use sed to extract the version part
          VERSION=$(echo "${{ steps.version_bump.outputs.newTag }}" | sed -e 's/.*v\(.*\)/v\1/')
          
          # Log the extracted version before setting it as output
          echo "Extracted Version: $VERSION"
          
          # Set the output value
          echo "::set-output name=version::$VERSION"

      - name: Build and publish the Docker image for ${{ github.repository }}
        uses: ./.github/actions/build-and-push
        with:
          image_name: ${{ github.repository }}/ops-backend # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.workspace }}/${{ env.WORKING_DIR }}
          dockerfile: ${{ github.workspace }}/${{ env.WORKING_DIR }}/${{ env.BE_DOCKER_FILE }}
          image_tags: "unstable,${{ github.sha }},${{ steps.extract_version.outputs.version }}"

  deploy-data-tools: 
    needs: build-data-tools

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      
      - name: Log in to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          creds:  ${{ secrets.SDLC_AZURE_CREDS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@5f5f4c56ca90376e3cfbd76ba8fe8533c784e655 # v2
        with:
          # azureCredentials: ${{ secrets.SDLC_AZURE_CREDS }}
          containerAppName: opre-ops-${{ env.ENVIRONMENT }}-data-tools
          resourceGroup: opre-ops-services-${{ env.ENVIRONMENT }}-app
          imageToDeploy: ghcr.io/hhs/opre-ops/ops-data-tools:${{ github.sha }}
        
  deploy-backend: 
    needs: build-backend

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      
      - name: Log in to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          creds:  ${{ secrets.SDLC_AZURE_CREDS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@5f5f4c56ca90376e3cfbd76ba8fe8533c784e655 # v2
        with:
            # azureCredentials: ${{ secrets.SDLC_AZURE_CREDS }}
            containerAppName: opre-ops-${{ env.ENVIRONMENT }}-backend
            resourceGroup: opre-ops-services-${{ env.ENVIRONMENT }}-app
            imageToDeploy: ghcr.io/hhs/opre-ops/ops-backend:${{ needs.build-backend.outputs.version }}
