name: Dev Test Tag and Build

on:
  workflow_dispatch:
  push:
    branches:
      - cml/bump-push
    paths:
      - 'backend/**'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Install dependencies
        run: npm install
        working-directory: ./.github/actions/bump-and-tag 

      - name:  'Automated Version Bump'
        uses: ./.github/actions/bump-and-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'ops-backend-v'
          OPENAPI_DIR:  'backend'
          PACKAGE_FILENAME:  'openapi.yml'
