name: Dev Data-Tools Pull Request Merged

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - backend/models/**
      - backend/data_tools/**
      - backend/Dockerfile.data-tools

env:
  TERRAFORM_VERSION: "1.6.6"
  TF_IN_AUTOMATION: "True"
  ENVIRONMENT: "dev"
  WORKING_DIR: "data-tools"

jobs:
  apply-deploy:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Terraform Apply
        uses: ./.github/actions/tf-apply
        with:
          terraform_directory: "terraform/eus/${{ env.ENVIRONMENT }}/${{ env.WORKING_DIR }}"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          azure_client_id: ${{ secrets.ARM_CLIENT_ID }}
          azure_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_id: ${{ github.event.pull_request.number }}
          plan_workflow_file: ${{ env.ENVIRONMENT }}_${{ env.WORKING_DIR }}_pr.yml
  