name: Deployment

on:
  push:
    branches:
      - development

jobs:

  development:
    name: Deploy to Development
    needs:
      - unit-tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/setup-javascript
      - uses: ./.github/actions/setup-cloudfoundry

      - name: Deploy Backend
        id: deploy-backend
        uses: ./.github/actions/deploy-backend
        with:
          USERNAME: ${{ secrets.DEV_USER }}
          PASSWORD: ${{ secrets.DEV_PASSWORD }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
          APP_NAME: ops-backend

      - name: Build frontend
        working-directory: ./frontend
        run: |
          echo ${{steps.deploy-backend.outputs.BACKEND_DOMAIN}}
          REACT_APP_BACKEND_DOMAIN=https://${{steps.deploy-backend.outputs.BACKEND_DOMAIN}} yarn build
          cp ./Staticfile ./build/

      - name: Deploy frontend
        uses: ./.github/actions/deploy-frontend
        with:
          USERNAME: ${{ secrets.DEV_USER }}
          PASSWORD: ${{ secrets.DEV_PASSWORD }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
          APP_NAME: ops-frontend
