name: Dev Test Tag and Build

on:
  workflow_dispatch:
  push:
    branches:
      - cml/bump-push
    paths:
      - 'backend/**'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Install dependencies
        run: npm install
        working-directory: ./.github/actions/bump-and-tag 

      - name:  'Automated Version Bump'
        id: version_bump
        uses: ./.github/actions/bump-and-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'ops-backend-v'
          OPENAPI_DIR: 'backend'
      
      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(echo "${{ steps.openapi_bump.outputs.newTag }}" | sed -e 's/.*v\(.*\)/v\1/')
          echo "::set-output name=version::$VERSION"
      
      - name: Use the New Tag and Version
        run: |
          echo "The new tag is ${{ steps.version_bump.outputs.newTag }}"
          echo "The new tag is ${{ steps.extract_version.outputs.version }}"
