name: Dev Test Tag and Build

on:
  workflow_dispatch:
  push:
    branches:
      - cml/bump-push
    paths:
      - 'frontend/**'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install
        working-directory: ./.github/actions/bump-and-tag 
      - name:  'Automated Version Bump'
        uses: ./.github/actions/bump-and-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'frontend-v'
          config_dir:  'frontend'
          config-filename: 'package.json'
          config-filetype: 'json'
