name: Deployment DEV

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches: [main, TechDebt-dev_deploy_main_push] # extra branch for testing only during dev.
  push:
    branches: [development]

jobs:

  deployment:
    permissions:
      contents: read

    # This uses a reusable_workflow a few special rules apply
    # see ref: https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows
    name: Deploy to cloud.gov
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      environment: cloud_gov_dev
      space: dev
    secrets: inherit # This will allow the jobs to inherit from the envrionment secrets; which are limited to only deployment items anyway.
