name: Deployment

on:
  push:
    branches:
      - development

jobs:

  development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run unit tests
        run: docker-compose run web pytest --cov-config=.coveragerc --cov=ops_site --cov-report term-missing
      - name: Install CF CLI
        run: |
          mkdir -p $HOME/bin
          export PATH=$HOME/bin:$PATH
          curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary" | tar xzv -C $HOME/bin
      - name: Deploy to Cloud.gov
        run: |
          export PATH=$HOME/bin:$PATH
          cf login -a https://api.fr.cloud.gov -u ${{ secrets.DEV_USER }} -p ${{ secrets.DEV_PASSWORD }} -o ${{ secrets.ORG_NAME }} -s ${{ secrets.SPACE_NAME }}
          echo "Login successful."
          cf push opre-ops-test -f manifest.yml
          echo "Deploy successful."
