name: Dev Frontend Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      
env:
  WORKING_DIR: "frontend"
  DOCKER_FILE: "Dockerfile.azure"
  ENVIRONMENT: dev

jobs:
  build-frontend:
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    # permissions:
    #   contents: write
    #   packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Install token dependencies
        run: npm install
        working-directory: ./.github/actions/generate-token

      - name: Generate GitHub App Token
        id: app-token
        uses: ./.github/actions/generate-token
        with:
          APP_ID: ${{ secrets.FLEXION_APP_ID }}
          PRIVATE_KEY: ${{ secrets.FLEXION_APP_PRIVATE_KEY }}
          INSTALLATION_ID: ${{ secrets.FLEXION_APP_INSTALLATION_ID }}

      - name:  'Automated Version Bump'
        id: version_bump
        uses:  'phips28/gh-action-bump-version@56588a3c4a1d62a068f308dfbc17f4ee55c69d41' #v11.0.4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          tag-prefix:  'ops-frontend-v'
          PACKAGEJSON_DIR:  'frontend'

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(echo "${{ steps.version_bump.outputs.newTag }}" | sed -e 's/.*v\(.*\)/v\1/')
          echo "::set-output name=version::$VERSION"

      - name: Build and publish the Docker image for ${{ github.repository }}
        uses: ./.github/actions/build-and-push
        with:
          image_name: ${{ github.repository }}/ops-${{ env.WORKING_DIR }} # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.workspace }}/${{ env.WORKING_DIR }}
          dockerfile: ${{ github.workspace }}/${{ env.WORKING_DIR }}/${{ env.DOCKER_FILE }}
          image_tags: "unstable,${{ github.sha }},${{ steps.extract_version.outputs.version }}"

  deploy-frontend: 
    needs: build-frontend

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
   
      - name: Log in to Azure
        uses: azure/login@6b2456866fc08b011acb422a92a4aa20e2c4de32 #v2.1.0
        with:
          creds:  ${{ secrets.AZURE_CREDS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@02d045129c058b13312276b50a552834cf74e2af # v2
        with:
            # azureCredentials: ${{ secrets.AZURE_CREDS }}
            containerAppName: opre-ops-${{ env.ENVIRONMENT }}-${{ env.WORKING_DIR }}
            resourceGroup: opre-ops-${{ env.ENVIRONMENT }}-app-rg
            imageToDeploy: ghcr.io/hhs/opre-ops/ops-${{ env.WORKING_DIR }}:${{ needs.build-frontend.outputs.version }}
