name: Dev Backend Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      
env:
  WORKING_DIR: "backend"
  DT_DOCKER_FILE: "Dockerfile.data-tools-import"
  BE_DOCKER_FILE: "Dockerfile.ops-api"
  ENVIRONMENT: dev

jobs:
  build-data-tools:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Build and publish the Docker image for ${{ github.repository }}
        uses: ./.github/actions/build-and-push
        with:
          image_name: ${{ github.repository }}/ops-data-tools # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.workspace }}/${{ env.WORKING_DIR }}
          dockerfile: ${{ github.workspace }}/${{ env.WORKING_DIR }}/${{ env.DT_DOCKER_FILE }}
          image_tags: "unstable,${{ github.sha }}"
  
  build-backend:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build and publish the Docker image for ${{ github.repository }}
        uses: ./.github/actions/build-and-push
        with:
          image_name: ${{ github.repository }}/ops-backend # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.workspace }}/${{ env.WORKING_DIR }}
          dockerfile: ${{ github.workspace }}/${{ env.WORKING_DIR }}/${{ env.BE_DOCKER_FILE }}
          image_tags: "unstable,${{ github.sha }}"

  deploy-data-tools: 
    needs: build-data-tools

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Log in to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          creds: ${{ secrets.SDLC_AZURE_CREDS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@5f5f4c56ca90376e3cfbd76ba8fe8533c784e655 # v2
        with:
          # azureCredentials: ${{ secrets.AZURE_CREDS }}
          containerAppName: opre-ops-${{ env.ENVIRONMENT }}-data-tools
          resourceGroup: opre-ops-services-${{ env.ENVIRONMENT }}-app
          imageToDeploy: ghcr.io/hhs/opre-ops/ops-data-tools:${{ github.sha }}
        
  deploy-backend: 
    needs: build-backend

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Log in to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          creds: ${{ secrets.SDLC_AZURE_CREDS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@5f5f4c56ca90376e3cfbd76ba8fe8533c784e655 # v2
        with:
            containerAppName: opre-ops-${{ env.ENVIRONMENT }}-backend
            resourceGroup: opre-ops-services-${{ env.ENVIRONMENT }}-app
            imageToDeploy: ghcr.io/hhs/opre-ops/ops-backend:${{ github.sha }}
