name: Nightly Security Analysis
on:
  workflow_dispatch:
  schedule:
    # cron format: 'minute hour dayofmonth month dayofweek'
    # this will run at 8AM UTC every day (3am EST / 4am EDT)
    - cron: '0 8 * * *'

jobs:
  dast-scan:
    name: OWASP Zap Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      # - id: setup
      #   uses: ./.github/actions/run-full-stack

      - name: Run OWASP Zap Scan on live-dev
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          #target: 'http://localhost:3000/'
          target: 'https://opre-ops-frontend-test.app.cloud.gov/'
          allow_issue_writing: false
          fail_action: false
          cmd_options: '-I'

      ## Manually reviewed the action, and validated it performs basic
      ## conversion from zap.json to zap.sarif.
      ## Reviewed by tdonaworth 08.09.2022
      - name: Create sarif file from zaproxy results
        uses: SvanBoxel/zaproxy-to-ghas@v1.0.2

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
