name: Nightly Security Analysis
on:
  workflow_dispatch:
  schedule:
    # cron format: 'minute hour dayofmonth month dayofweek'
    # this will run at 8AM UTC every day (3am EST / 4am EDT)
    - cron: '0 8 * * *'

jobs:
  dast-scan:
    name: OWASP Zap Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: setup
        uses: ./.github/actions/run-full-stack

      - name: Run OWASP Zap Scan on live-dev
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:3000/'
          allow_issue_writing: false
          fail_action: false
          cmd_options: '-I'
