name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      security-events: write
    name: Semgrep Analyze
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:25b0692015c29b7b520517da6356c521aff9691fad0b56df69f66bfaf9f0d20c # 1.47.0
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      # We've changed the behavior a little, instead of forcing a fail on `semgrep scan` step
      # we force the upload, and manage any results in the sencondary CodeQL Analysis of the
      # uploaded files. Configuration is handled in Settings --> Security --> CodeQL
      - name: Semgrep Scan
        run: |
          echo "SEMGREP_TO_UPLOAD=semgrep.sarif" >> $GITHUB_ENV
          semgrep scan --sarif --output=semgrep.sarif --exclude="frontend/src/uswds" --metrics=off
        env:
          SEMGREP_RULES: "p/default"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@662472033e021d55d94146f66f6058822b0b39fd # v3
        with:
          sarif_file: ${{ env.SEMGREP_TO_UPLOAD }}
        if: always()
