name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      security-events: write
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semgrep Scan
        run: semgrep ci --sarif --output=semgrep.sarif

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
