name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      security-events: write
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semgrep Scan
        run: semgrep scan --sarif --output=semgrep.sarif --error
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_RULES: "p/default"

        # There's a bug in semgrep that even if there are ignored findings, there will still be a SARIF file created that has the findings.
        # So, if we get to this step, the previous scan step succeeded, and we actually don't have any findings.
        # Delete the findings in the SARIF file.
      - name: Install jq
        run: |
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /usr/local/bin/jq
          chmod +x /usr/local/bin/jq

      - name: SARIF clean-up
        run: cat ./semgrep.sarif | jq 'del(.runs[].results[])' > semgrep.sarif

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
