name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      actions: write
      security-events: write
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semgrep Scan
        run: semgrep scan --sarif --output=semgrep.sarif --error
        env:
          SEMGREP_RULES: p/default

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
