name: Deployment STAGING

on:
  # Deploy to STAGING nightly, since DEV is updated on each PUSH. This will ensure STAGING remains close to DEV
  # but doesn't conflict with daily testing.
  schedule:
    # cron format: 'minute hour dayofmonth month dayofweek'
    # this will run at 8AM UTC every day (3am EST / 4am EDT)
    - cron: '0 8 * * *'
  push:
    branches:
      - staging
    paths-ignore:
      - '.github/**' # We don't want to trigger a deployment when we update the workflows.
      - 'docs/**' # We don't want to trigger a deployment when we update the docs.
      - '*.md'

jobs:

  deployment:
    permissions:
      contents: read

    # This uses a reusable_workflow a few special rules apply
    # see ref: https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows
    name: Deploy to cloud.gov
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      environment: cloud_gov_staging
      space: staging
    secrets: inherit # This will allow the jobs to inherit from the envrionment secrets; which are limited to only deployment items anyway.
