name: Test Build

on:
  push:
    branches:
      - POC-Azure-Deployment
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test Docker Context
        uses: ./.github/workflows/build-and-push-docker-image.yaml
        with:
          image-name: ops-backend
          docker-context: backend
          docker-file: Dockerfile.ops-api
