name: Test Backend Build

on:
  push:
    branches:
      - POC-Azure-Deployment
    paths:
      - backend/models/**
      - backend/ops_api/**
      - backend/Dockerfile.cg-ops-api
  workflow_dispatch:

jobs:
  test-build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build_and_push.yaml
    with:
      image-name: ops-backend
      docker-context: backend
      docker-file: Dockerfile.ops-api