name: Test Build

on:
  push:
    branches:
      - POC-Azure-Deployment
  workflow_dispatch:

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - name: Test Docker Context
#         uses: ./.github/workflows/build_and_push.yaml
#         with:
#           image-name: ops-backend
#           docker-context: backend
#           docker-file: Dockerfile.ops-api
jobs:
  test-build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build_and_push.yaml
    with:
      image-name: ops-backend
      docker-context: backend
      docker-file: Dockerfile.ops-api