name: Build Components

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  set-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        event: ["push", "pull_request"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Matrix and Build
        id: set-matrix
        uses: ./.github/actions/test_matrix
        with:
          event: ${{ matrix.event }}

  use-matrix:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - name: Use matrix
        run: |
          echo "Component: ${{ matrix.components }}"
          echo "Paths: ${{ matrix.paths }}"
          echo "Dockerfile: ${{ matrix.docker_files }}"
          echo "Working Directory: ${{ matrix.working_dirs }}"
          echo "Image Name: ${{ matrix.image_names }}"
