name: Test Frontend Build

on:
  push:
    branches:
      - POC-Azure-Deployment
    # paths:
    #   - 'frontend/**'
  workflow_dispatch:

jobs:
  test-build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build_and_push.yaml
    with:
      image-name: ops-frontend
      docker-context: frontend
      docker-file: Dockerfile.azure