on:
  workflow_call:

jobs:

  backend-api:
    name: Backend API Unit Tests
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: "__blank__"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./.github/actions/setup-python
      # Stand up the system stack, to have something to poke
      - name: Run backend unit tests
        working-directory: ./backend/ops_api/
        run: pipenv run pytest

  backend-data-tools:
    name: Data-Tools Unit Tests
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: "__blank__"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./.github/actions/setup-python
      - name: Run backend unit tests
        working-directory: ./backend/data_tools/
        run: pipenv install --dev && pipenv run pytest


  frontend:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./.github/actions/setup-javascript
      # Stand up the system stack, to have something to poke
      - name: Run frontend unit tests
        working-directory: ./frontend
        run: yarn test

  e2e:
    name: End-to-End Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: ./.github/actions/setup-javascript
      # Stand up the system stack, to have something to poke
      - uses: ./.github/actions/run-full-stack
      # Run the Cypress E2E Tests
      - name: E2E Test
        working-directory: frontend
        run: yarn test:e2e
