on:
  workflow_call:

## This ensures only a single job is running at a time.
## This will specifically kill the long e2e if another
## commit occors on the pull_request or any other conflicting job
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  backend:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run backend unit tests
        working-directory: ./backend
        run: pipenv run pytest

  frontend:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-javascript
      - name: Run frontend unit tests
        working-directory: ./frontend
        run: yarn test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: ./.github/actions/setup-javascript
      # Stand up the system stack, to have something to poke
      - uses: ./.github/actions/run-full-stack
      # Run the Cypress E2E Tests
      - name: E2E Test
        working-directory: frontend
        run: yarn test:e2e
