on:
  workflow_call:

jobs:

  backend:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pipenv
      # - name: Pipenv install
      #   run: pip install pipenv
      # - name: Install backend dependencies
      #   working-directory: ./backend
      #   run: pipenv install --dev
      - name: Build containers
        working-directory: ./backend
        run: docker-compose build
      - name: Run backend unit tests
        working-directory: ./backend
        run: |
          PYTHONPATH=. docker-compose run backend pytest --cov-config=.coveragerc --cov=ops_site --cov-report term-missing
  frontend:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile
      - name: Run frontend unit tests
        working-directory: ./frontend
        run: yarn test
