on:
  workflow_call:

jobs:
  backend-api:
    name: Backend API Unit Tests
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: "__blank__"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup-python
      # Stand up the system stack, to have something to poke
      - name: Run backend unit tests
        working-directory: ./backend/ops_api/
        run: pipenv run pytest

  backend-data-tools:
    name: Data-Tools Unit Tests
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: "__blank__"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup-python
      - name: Run backend unit tests
        working-directory: ./backend/data_tools/
        run: pipenv install --dev && pipenv run pytest

  frontend:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup-javascript
      # Stand up the system stack, to have something to poke
      - name: Run frontend unit tests
        working-directory: ./frontend
        run: bun run test

  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - id: set-matrix
        run: |
          echo 'FILES<<EOF' >> $GITHUB_ENV
          ls cypress/e2e/*.cy.js >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

  e2e:
    name: End-to-End Testing
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: ./.github/actions/setup-javascript

      # Stand up the system stack, to have something to poke
      - name: Launch Stack
        uses: ./.github/actions/run-full-stack
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}

      # Install Cypress globally
      - name: Install Cypress globally
        run: bun install -g cypress

      # Run the Cypress E2E Tests
      - name: E2E Test
        working-directory: frontend
        run: bun run cypress install && bun run cypress run --config-file ./cypress.config.js --headless --spec ${{ matrix.file }}

      # Upload Cypress screenshots as artifact if a test fails
      - name: Upload screenshots if failure
        if: failure() # This step will run only if the previous step fails
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          path: frontend/cypress/screenshots # Update this path based on your project structure
          name: cypress-screenshots

      # Capture logs from all services
      - name: Capture logs
        shell: bash
        if: always()
        run: | # Capture logs from all services
          docker compose -f docker-compose.yml logs --no-color > full-stack-logs.log

      # Upload logs as artifact
      - name: Upload logs as artifact
        if: always() # Ensure this runs, even if E2E fails
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          # Set the path to the log file
          path: full-stack-logs.log
          # Optionally, set a name for the artifact
          name: full-stack-logs
